### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by borazslo** [martonfekete/ukrainehelp#8]
I think it's very important to publish that our informations are from a reliable source and the informations is not outdated yet. 

I've began to use this syntax:
`<small>({{SOURCE}}: [{{SOURCE_NAME_PLACEHOLDER}}](url), m/dd/yyyy)</small>`

What tou you think about using some kind of small icon only so as to make the text cleaner. The small icon could show a popup on mosueover, and it opens the source onclick. The syntax could be something like this befor the templater:
`<source href="url" name="{{SOURCE_NAME_PLACEHOLDER}}" date="mm/dd/yyyy">`

What do you think?

**Comment by martonfekete** [comment]
Great idea. Pushed a solution.

I added a markdown url format, `[ref_LABEL](url###DATE)` that allows an automatic rendering of references. Further info in the README.
